---

optimizer:
  name: hebbian
  params:
    thresh: 0.5

metrics:
  - name: basis_set_size
    save: True
  - name: basis_set_size_increase
    save: False
  - name: exact_match_accuracy
    save: True
  - name: approximate_match_accuracy
    save: True

dataloader:
  batch_size: 1
  shuffle: True

training:
  num_epochs: 1
...