---

optimizer:
  name: hebbian
  params: {}
metrics:
  - name: basis_set_size
    save: True
  - name: basis_set_size_increase
    save: False
  - name: match_accuracy
    save: True
    #reduction: mean
  #- ##name: match_accuracy
  #  save: True

dataloader:
  batch_size: 4
  shuffle: True

training:
  num_epochs: 1

#verbosity: 
...