---

optimizer:
  name: hebbian
  params: {}
metrics:
  - name: basis_set_size
    save: True
  - name: basis_set_size_increase
    save: False
  - name: basis_average
    save: True

dataloader:
  batch_size: 4
  shuffle: True

training:
  num_epochs: 1

#verbosity: 
...